Default: &defaults
  database: ysql.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ysql_test.sqlite3
  <<: *defaults

Staging:
  database: ysql_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ysql_production.sqlite3
  poolsize: 100
  <<: *defaults
