Default: &defaults
  database: yggdrasil.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yggdrasil_test.sqlite3
  <<: *defaults

Staging:
  database: yggdrasil_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: /var/yggdrasil/yggdrasil_production.sqlite3
  poolsize: 100
  <<: *defaults
